// Generated by CoffeeScript 1.8.0
(function() {
  window.Persion = (function() {
    function Persion(name) {
      this.name = name;
    }

    Persion.prototype.possessiveName = function() {
      var _ref;
      if ((_ref = this.name[this.name.length - 1]) === 'x' || _ref === 's' || _ref === 'z') {
        return "" + this.name + "'";
      } else {
        return "" + this.name + "'s";
      }
    };

    return Persion;

  })();

}).call(this);
