// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PetView = (function(_super) {
    __extends(PetView, _super);

    function PetView(pet) {
      this.pet = pet;
    }

    PetView.prototype.formattedDescription = function() {
      var _ref;
      return ("<h2> " + this.pet.name + " </h2>") + ("<h3 class='breed'> " + this.pet.breed + " ") + ("(" + ((_ref = this.pet.age) != null ? _ref : "??") + " years old)</h3>") + this.imageTag(this.pet.image) + ("<p class='description'> " + this.pet.description + "</p>");
    };

    PetView.prototype.formatPatName = function(showBehavior) {
      var action, behavior, cssClass, result, sound, _ref, _ref1;
      result = this.pet.name;
      if (showBehavior) {
        _ref = this.pet.behaviors(), sound = _ref[0], action = _ref[1];
        _ref1 = sound != null ? ["" + sound + "!", "sound"] : [action, "action"], behavior = _ref1[0], cssClass = _ref1[1];
        result += "<span class='" + cssClass + "'>" + (behavior.toLowerCase()) + "</span>";
      }
      return result;
    };

    PetView.prototype.formattedLink = function(i, showBehavior) {
      if (showBehavior == null) {
        showBehavior = true;
      }
      return ("<a href='#' onclick='selectPet(" + i + ",this)'>") + ("" + (this.formatPatName(showBehavior)) + "</a>");
    };

    return PetView;

  })(View);

}).call(this);
