// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PetListView = (function(_super) {
    __extends(PetListView, _super);

    function PetListView(views, featuredPets) {
      this.views = views;
      this.featuredPets = featuredPets;
      this.featured = featuredPets;
    }

    PetListView.prototype.render = function() {
      this.renderList();
      this.renderFilteringBar();
      this.renderFeatured();
      window.listView = this;
      window.displayPetlist = function(filterType) {
        return window.listView.renderList(filterType);
      };
      return window.selectPet = function(index, element) {
        return window.listView.selectPet(index, element);
      };
    };

    PetListView.prototype.renderList = function(filter) {
      var i, petOutput, view;
      petOutput = (function() {
        var _i, _len, _ref, _results;
        _ref = this.views;
        _results = [];
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          view = _ref[i];
          if (view.pet.matchesFilter(filter)) {
            _results.push("<li>" + (view.formattedLink(i)) + "</li>");
          }
        }
        return _results;
      }).call(this);
      return this.renderToElement("available_pets", petOutput.join(""));
    };

    PetListView.prototype.selectPet = function(petIndex, element) {
      var link, petView, _i, _len, _ref;
      petView = this.views[petIndex];
      this.renderToElement("pet_information", petView.formattedDescription());
      _ref = $("#available_pets a");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        link = _ref[_i];
        link.className = "";
      }
      return element.className = "selected";
    };

    PetListView.prototype.renderFeatured = function() {
      var chosenPetIndex, chosenPetName, chosenPetView, fullListIndex, i, view, _i, _len, _ref, _ref1;
      if (this.featured == null) {
        return;
      }
      chosenPetIndex = Math.floor(Math.random() * this.featured.length);
      chosenPetName = this.featured[chosenPetIndex];
      _ref = this.views;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        view = _ref[i];
        if (view.pet.name === chosenPetName) {
          _ref1 = [view, i], chosenPetView = _ref1[0], fullListIndex = _ref1[1];
        }
      }
      return this.renderToElement("featured", "<span class='title'> Featured Pet </span>" + chosenPetView.formattedLink(fullListIndex, false));
    };

    PetListView.prototype.renderFilteringBar = function() {
      var filteringOutput, type;
      filteringOutput = (function() {
        var _i, _len, _ref, _results;
        _ref = Animal.CATEGORIES;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          type = _ref[_i];
          _results.push("<li> <a href='#' onclick='displayPetlist(\"" + type + "\")'>" + type + "</a></li>");
        }
        return _results;
      })();
      return this.renderToElement("filtering_ops", filteringOutput.join(""));
    };

    return PetListView;

  })(View);

}).call(this);
