// Generated by CoffeeScript 1.8.0
(function() {
  var animalBehaviors, displayFeatured, filteringOutput, formatDescription, formatPatName, formatPetLink, imageTag, petTypes, shop, type,
    __slice = [].slice;

  shop = {
    owner: {
      name: "Jdd"
    },
    animals: [
      {
        name: "Kelsey",
        type: "dog",
        age: 3,
        breed: "Labrador",
        description: "A sweet and loyal dog. Loves to play fetch. Sometimes drinks out of the toilet."
      }, {
        name: "Sgt. Snuffles",
        type: "dog",
        breed: "Pug",
        description: "Small in stature, but big in heart, Sgt. Snuffles is never one to back down from a mission."
      }, {
        name: "Chomps",
        type: "rabbit",
        age: 4,
        breed: "Giant Angora",
        description: "Chomps is usually very good-natured, but he does not take kindly to being mistaken for an ottoman. Come see him in person and you'll understand why that may happen."
      }, {
        name: "Flops",
        type: "rabbit",
        age: 2,
        breed: "French Lop",
        image: "flops.jpg",
        description: "Enjoys nothing more than a good roll in the grass and a nap in the sun."
      }, {
        name: "Bopper",
        type: "rabbit",
        breed: "Checkered Giant",
        description: "The quiet one of the group. Loves celery."
      }, {
        name: "Chairman Meow",
        type: "cat",
        breed: "Snowshoe",
        description: "True to his name, Chairman Meow fancies himself in charge."
      }, {
        name: "Jacques",
        type: "cat",
        age: 1.5,
        breed: "Manx",
        description: "A happy-go-lucky cat who occasionally finds himself at odds with Chairman Meow over who gets to sit at the top of the cat tree."
      }, {
        name: "Chupa",
        type: "cat",
        breed: "Scottish Fold",
        image: "chupa.jpg",
        description: "Chupa always appears perplexed with the world, but don't be fooled. That's just the way his face is shaped."
      }, {
        name: "Alfred",
        type: "horse",
        age: 3.5,
        breed: "Breton",
        description: "The resident shop patriarch. Very calm and tolerates the antics of the other animals when they sneak into his pen."
      }
    ]
  };

  $("#owner_name").append(shop.owner.name);

  $(document).attr("title", "" + shop.owner.name + " 's Pet Shop");

  formatDescription = function(pet) {
    var _ref;
    return ("<h2> " + pet.name + " </h2>") + ("<h3 class='breed'> " + pet.breed + " ") + ("(" + ((_ref = pet.age) != null ? _ref : "??") + " years old)</h3>") + imageTag(pet.image) + ("<p class='description'> " + pet.description + "</p>");
  };

  imageTag = function(filename) {
    if (filename != null) {
      return "<img src='images/" + filename + "' />";
    } else {
      return "";
    }
  };

  window.selectPet = function(petIndex, element) {
    var link, pet, _i, _len, _ref;
    pet = shop.animals[petIndex];
    $("#pet_information").html(formatDescription(pet));
    _ref = $("#available_pets a");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      link = _ref[_i];
      link.className = "";
    }
    return element.className = "selected";
  };

  animalBehaviors = function(animal) {
    switch (animal.type) {
      case "cat":
        return ["meow", null];
      case "dog":
        return ["bark", "wag"];
      case "rabbit":
        return [null, "hop,hop"];
      case "horse":
      case "donkey":
        return ["neigh", null];
      default:
        return [null, null];
    }
  };

  formatPatName = function(pet, showBehavior) {
    var action, behavior, cssClass, result, sound, _ref, _ref1;
    result = pet.name;
    if (showBehavior) {
      _ref = animalBehaviors(pet), sound = _ref[0], action = _ref[1];
      _ref1 = sound != null ? ["" + sound + "!", "sound"] : [action, "action"], behavior = _ref1[0], cssClass = _ref1[1];
      result += "<span class='" + cssClass + "'>" + (behavior.toLowerCase()) + "</span>";
    }
    return result;
  };

  formatPetLink = function(pet, i, showBehavior) {
    if (showBehavior == null) {
      showBehavior = true;
    }
    return ("<a href='#' onclick='selectPet(" + i + ",this)'>") + ("" + (formatPatName(pet, showBehavior)) + "</a>");
  };

  window.displayPetlist = function(filter) {
    var i, pet, petOutput;
    if (filter == null) {
      filter = "All";
    }
    petOutput = (function() {
      var _i, _len, _ref, _results;
      _ref = shop.animals;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        pet = _ref[i];
        if (filter === "All" || filter.toLowerCase() === pet.type) {
          _results.push("<li>" + (formatPetLink(pet, i)) + "</li>");
        }
      }
      return _results;
    })();
    return $("#available_pets").html(petOutput.join(""));
  };

  window.displayPetlist();

  petTypes = ['All', 'Dog', 'Cat', 'Rabbit', 'Horse'];

  filteringOutput = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = petTypes.length; _i < _len; _i++) {
      type = petTypes[_i];
      _results.push("<li> <a href='#' onclick='displayPetlist(\"" + type + "\")'>" + type + "</a></li>");
    }
    return _results;
  })();

  $("#filtering_ops").html(filteringOutput.join(""));

  displayFeatured = function() {
    var chosenPet, chosenPetIndex, chosenPetName, featurePets, fullListIndex, i, pet, _i, _len, _ref, _ref1;
    featurePets = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    chosenPetIndex = Math.floor(Math.random() * featurePets.length);
    chosenPetName = featurePets[chosenPetIndex];
    _ref = shop.animals;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      pet = _ref[i];
      if (pet.name === chosenPetName) {
        _ref1 = [pet, i], chosenPet = _ref1[0], fullListIndex = _ref1[1];
      }
    }
    return $("#featured").html("<span class='title'> Featured Pet </span>" + formatPetLink(chosenPet, fullListIndex, false));
  };

  displayFeatured("Chupa", "Kelsey", "Flops");

}).call(this);
