// Generated by CoffeeScript 1.8.0
(function() {
  var mainView, pet, petListView, petViews, shop;

  shop = {
    owner: new Persion("Jdd"),
    animals: Animal.loadSeedData(),
    featured: ["Chupa", "Kelsey", "Flops"]
  };

  petViews = (function() {
    var _i, _len, _ref, _results;
    _ref = shop.animals;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      pet = _ref[_i];
      _results.push(new PetView(pet));
    }
    return _results;
  })();

  petListView = new PetListView(petViews, shop.featured);

  mainView = new ShopView(shop.owner, petListView);

  mainView.render();

}).call(this);
