// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ShopView = (function(_super) {
    __extends(ShopView, _super);

    function ShopView(owner, mainContent) {
      this.owner = owner;
      this.mainContent = mainContent;
    }

    ShopView.prototype.render = function() {
      this.renderToElement("owner_name", this.owner.possessiveName());
      document.title = "" + (this.owner.possessiveName()) + " Pet Shop";
      return this.mainContent.render();
    };

    return ShopView;

  })(View);

}).call(this);
