// Generated by CoffeeScript 1.8.0
(function() {
  window.View = (function() {
    function View() {}

    View.prototype.renderToElement = function(id, output) {
      return $("#" + id).html(output);
    };

    View.prototype.imageTag = function(fileName) {
      if (fileName != null) {
        return "<img src='images/" + fileName + "' />";
      } else {
        return "";
      }
    };

    return View;

  })();

}).call(this);
